# Build Environment
build_environment: Ubuntu 14.04

# language setting
language: php

# php tag
php:
 - 5.4

install:
 - mv app/config/parameters.yml.dist app/config/parameters.yml
 - composer self-update
 - composer install
 - php app/console cache:clear --env=test

script: bin/behat
