# Build Environment
build_environment: Ubuntu 14.04

# language setting
language: php

# php tag
php:
 - 5.4
 - 5.5

install:
 - mv app/config/parameters.yml.dist app/config/parameters.yml
 - composer self-update
 - composer install
 - php app/console cache:clear --env=test
 - mkdir -p shippable/testresults

script: bin/behat --format=junit --out shippable/testresults
