imports:
    - { resource: config_dev.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

swiftmailer:
    delivery_address: 'systemsupport@ice.cam.ac.uk'