imports:
    - { resource: config_dev.yml }

parameters:
    janus_api_password: password

framework:
    test: ~
    trusted_proxies: [127.0.0.1]
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db

liip_functional_test:
    cache_sqlite_db: true
