Ice\ExternalUserBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        title:
            expose: true
        firstNames:
            expose: true
            serialized_name: firstNames
        lastName:
            expose: true
            serialized_name: lastName
        dob:
            expose: true