Ice\ExternalUserBundle\Entity\User:
    properties:
        email:
            - NotBlank:
                groups: [rest_register, rest_update]
                message: Please provide an email address
            - Email:
                groups: [rest_register, rest_update]
                message: Please provide a valid email address

        plainPassword:
            - NotBlank:
                groups: [rest_register]
                message: Please provide a password
            - Length:
                groups: [rest_register]
                min: 6
                minMessage: Your password must be at least six characters long
