Ice\ExternalUserBundle\Entity\User:
    properties:
        title:
            - NotBlank:
                groups: [rest_register]
                message: Please provide your title

        firstNames:
            - NotBlank:
                groups:  [rest_register]
                message: Please provide your first name(s)

        lastName:
            - NotBlank:
                groups: [rest_register]
                message: Please provide your last name

        dob:
            - Date:
                groups: [rest_register]
                message: Please provide a valid date of birth

        email:
            - NotBlank:
                groups: [rest_register]
                message: Please provide an email address
            - Email:
                groups: [rest_register]
                message: Please provide a valid email address

        plainPassword:
            - NotBlank:
                groups: [rest_register]
                message: Please provide a password
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [emailCanonical]
            groups: [rest_register]
            message: This email address is already associated with another account
