Ice\ExternalUserBundle\Entity\User:
    properties:
        email:
            - Email:
                groups: [rest_register, rest_update]
                message: Please provide a valid email address

        plainPassword:
            - NotBlank:
                groups: [rest_register, rest_set_password]
                message: Please provide a password
            - Length:
                groups: [rest_register, rest_set_password]
                min: 6
                # https://github.com/symfony/symfony/issues/4267
                minMessage: Your password must be at least six characters long|Your password must be at least six characters long
